# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = app_admin1
DESTDIR = ../../bin/vc_ms_dbd_WIN32_10
QT += core xml xmlpatterns uitools gui
CONFIG += debug
DEFINES += QT_LARGEFILE_SUPPORT QT_XML_LIB QT_XMLPATTERNS_LIB
INCLUDEPATH += $(BOOST_DIR) \
    ./../../include
LIBS += -L"./../../lib/boost/$(Configuration)" \
    -L"./../../lib/$(Configuration)" \
    -llibnskernel \
    -llibnsadmin \
    -llibmeta \
    -llibboost_system-vc100-mt-gd-1_54 \
    -llibboost_date_time-vc100-mt-gd-1_54 \
    -llibboost_filesystem-vc100-mt-gd-1_54 \
    -llibboost_iostreams-vc100-mt-gd-1_54 \
    -llibboost_program_options-vc100-mt-gd-1_54 \
    -llibboost_regex-vc100-mt-gd-1_54 \
    -llibboost_thread-vc100-mt-gd-1_54 \
    -llibGLESv2d
DEPENDPATH += .
MOC_DIR += /GeneratedFiles/vc_ms_dbd_win32_10
OBJECTS_DIR += vc_ms_dbd_win32_10
UI_DIR += /GeneratedFiles
RCC_DIR += /GeneratedFiles
include(app_admin1.pri)
TRANSLATIONS += app_admin1_ru.ts
