# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../../include_program/app_admin1/gui/admin_configer.h \
    ../../include_program/app_admin1/gui/interfaceproccessor.h \
    ../../include_program/app_admin1/gui/interfacetransaction.h \
    ../../include_program/app_admin1/gui/RU_dict.h \
    ../../include_program/app_admin1/gui/uiwidgetitem.h \
    ../../include_program/app_admin1/gui/form_addserver.h \
    ../../include_program/app_admin1/gui/form_admin.h \
    ../../include_program/app_admin1/gui/form_esdfilter.h \
    ../../include_program/app_admin1/gui/form_filter.h \
    ../../include_program/app_admin1/gui/form_getstring.h \
    ../../include_program/app_admin1/gui/form_import.h \
    ../../include_program/app_admin1/gui/form_setvalue.h \
    ../../include_program/app_admin1/gui/uiuitil.h \
    ../../include_program/app_admin1/gui/viewmodels.h
SOURCES += ../../include_program/app_admin1/main.cpp \
    ../../include_program/app_admin1/gui/admin_configer.cpp \
    ../../include_program/app_admin1/gui/form_addserver.cpp \
    ../../include_program/app_admin1/gui/form_admin.cpp \
    ../../include_program/app_admin1/gui/form_esdfilter.cpp \
    ../../include_program/app_admin1/gui/form_filter.cpp \
    ../../include_program/app_admin1/gui/form_getstring.cpp \
    ../../include_program/app_admin1/gui/form_import.cpp \
    ../../include_program/app_admin1/gui/form_setvalue.cpp \
    ../../include_program/app_admin1/gui/interfaceproccessor.cpp \
    ../../include_program/app_admin1/gui/RU_dict.cpp \
    ../../include_program/app_admin1/gui/uiuitil.cpp \
    ../../include_program/app_admin1/gui/uiwidgetitem.cpp \
    ../../include_program/app_admin1/gui/viewmodels.cpp
FORMS += ../../include_program/app_admin1/gui/form_addserver.ui \
    ../../include_program/app_admin1/gui/form_admin.ui \
    ../../include_program/app_admin1/gui/form_esdfilter.ui \
    ../../include_program/app_admin1/gui/form_filter.ui \
    ../../include_program/app_admin1/gui/form_getstring.ui \
    ../../include_program/app_admin1/gui/form_import.ui \
    ../../include_program/app_admin1/gui/form_setvalue.ui
TRANSLATIONS += ./app_admin1_ru.ts
RESOURCES += ../../include_program/app_admin1/resourse/mainresource.qrc
