#include "RU_dict.h"

namespace dvnci {
    namespace admin {

        void load_dictionary(wstringtranslate_map& map_) {

//#ifndef NS_ADMIN_RELEASE_BAG

            
            map_.insert(wstringtranslate_pair("properties.17", "Путь"));
            map_.insert(wstringtranslate_pair("properties.18", "Имя"));
            map_.insert(wstringtranslate_pair("properties.19", "Коментарий"));
            map_.insert(wstringtranslate_pair("properties.20", "OC"));
            map_.insert(wstringtranslate_pair("properties.21", "GLOBALMAPSIZE"));
            map_.insert(wstringtranslate_pair("properties.22", "СУБД"));
            map_.insert(wstringtranslate_pair("properties.23", "Строка подключения"));
            map_.insert(wstringtranslate_pair("properties.24", "Буферезация"));
            map_.insert(wstringtranslate_pair("properties.25", "Хранение архивов мес."));
            map_.insert(wstringtranslate_pair("properties.26", "Уровень отладки"));
            map_.insert(wstringtranslate_pair("properties.27", "Имя администратора"));
            map_.insert(wstringtranslate_pair("properties.28", "Пароль администратора"));
            map_.insert(wstringtranslate_pair("properties.29", "Admin port"));
            map_.insert(wstringtranslate_pair("properties.30", "Remote port"));
            map_.insert(wstringtranslate_pair("properties.31", "xmlopc port"));
            map_.insert(wstringtranslate_pair("properties.885", "Сервер"));
            map_.insert(wstringtranslate_pair("properties.887", "Топик"));
            map_.insert(wstringtranslate_pair("properties.128", "Имя"));
            map_.insert(wstringtranslate_pair("properties.130", "Путь"));
            map_.insert(wstringtranslate_pair("properties.132", "Тип запуска"));
            map_.insert(wstringtranslate_pair("properties.256", "Имя"));
            map_.insert(wstringtranslate_pair("properties.258", "Этикетка типа"));
            map_.insert(wstringtranslate_pair("properties.257", "Имя"));
            map_.insert(wstringtranslate_pair("properties.272", "Пользователь"));
            map_.insert(wstringtranslate_pair("properties.274", "Пароль"));
            map_.insert(wstringtranslate_pair("properties.275", "IP Фильтр"));            
            map_.insert(wstringtranslate_pair("properties.276", "Роль"));
            map_.insert(wstringtranslate_pair("properties.277", "Уровень доступа"));            
            map_.insert(wstringtranslate_pair("properties.288", "Имя"));
            map_.insert(wstringtranslate_pair("properties.289", "Пользователь"));
            map_.insert(wstringtranslate_pair("properties.290", "Хост"));
            map_.insert(wstringtranslate_pair("properties.291", "Appid"));
            map_.insert(wstringtranslate_pair("properties.292", "Доступ"));
            map_.insert(wstringtranslate_pair("properties.293", "Уровень доступа"));
            map_.insert(wstringtranslate_pair("properties.294", "IP Фильтр"));
            map_.insert(wstringtranslate_pair("properties.295", "Роль"));            
            map_.insert(wstringtranslate_pair("properties.512", "Коментарий"));
            map_.insert(wstringtranslate_pair("properties.592", "Сообщение"));
            map_.insert(wstringtranslate_pair("properties.4688", "Тип доступа"));
            map_.insert(wstringtranslate_pair("properties.337", "Тип"));
            map_.insert(wstringtranslate_pair("properties.768", "Привязка"));
            map_.insert(wstringtranslate_pair("properties.881", "Хост"));
            map_.insert(wstringtranslate_pair("properties.883", "IPaddr/Host"));
            map_.insert(wstringtranslate_pair("properties.883", "Имя сервера"));
            map_.insert(wstringtranslate_pair("properties.867", "IP"));
            map_.insert(wstringtranslate_pair("properties.868", "IPv6"));
            map_.insert(wstringtranslate_pair("properties.869", "Номер com-порта"));
            map_.insert(wstringtranslate_pair("properties.897", "Протокол"));
            map_.insert(wstringtranslate_pair("properties.1122", "Номер устойства"));
            map_.insert(wstringtranslate_pair("properties.1138", "Имя группы"));
            map_.insert(wstringtranslate_pair("properties.1137", "Пользователь"));
            map_.insert(wstringtranslate_pair("properties.1153", "Пароль"));
            map_.insert(wstringtranslate_pair("properties.1024", "Единицы изм. контролера min"));
            map_.insert(wstringtranslate_pair("properties.1025", "Стартовый период предыстории"));
            map_.insert(wstringtranslate_pair("properties.1140", "Версия протокола"));
            map_.insert(wstringtranslate_pair("properties.1142", "Метод опроса"));
            map_.insert(wstringtranslate_pair("properties.1144", "Поддержка HDA"));
            map_.insert(wstringtranslate_pair("properties.1145", "Domain"));
            map_.insert(wstringtranslate_pair("properties.1154", "Скорость общения"));
            map_.insert(wstringtranslate_pair("properties.1156", "Databit"));
            map_.insert(wstringtranslate_pair("properties.1158", "Stopbit"));
            map_.insert(wstringtranslate_pair("properties.1159", "Контроль четности"));
            map_.insert(wstringtranslate_pair("properties.1160", "Flowcontrol"));
            map_.insert(wstringtranslate_pair("properties.1161", "FCntrlAfter ms."));
            map_.insert(wstringtranslate_pair("properties.1162", "FCntrlBefore ms."));
            map_.insert(wstringtranslate_pair("properties.1163", "RI ms."));
            map_.insert(wstringtranslate_pair("properties.1164", "RTM ms."));
            map_.insert(wstringtranslate_pair("properties.1165", "RTC ms."));
            map_.insert(wstringtranslate_pair("properties.1166", "WTM ms."));
            map_.insert(wstringtranslate_pair("properties.1166", "WTC ms."));
            map_.insert(wstringtranslate_pair("properties.1280", "Единицы изм. контролера max"));
            map_.insert(wstringtranslate_pair("properties.1281", "Смещение подпериода"));
            map_.insert(wstringtranslate_pair("properties.1379", "Таймаут"));
            map_.insert(wstringtranslate_pair("properties.1381", "Мертвая зона группы%"));
            map_.insert(wstringtranslate_pair("properties.1383", "Период обновления "));
            map_.insert(wstringtranslate_pair("properties.1385", "Синхронизация времени"));
            map_.insert(wstringtranslate_pair("properties.1387", "Размер блока"));
            map_.insert(wstringtranslate_pair("properties.1388", "Размер архивного блока"));
            map_.insert(wstringtranslate_pair("properties.1389", "Попыток чтения"));
            map_.insert(wstringtranslate_pair("properties.1391", "Таймаут индикации"));
            map_.insert(wstringtranslate_pair("properties.1408", "Кодировка"));
            map_.insert(wstringtranslate_pair("properties.1536", "Мертвая зона%"));
            map_.insert(wstringtranslate_pair("properties.912", "Масштабировать"));
            map_.insert(wstringtranslate_pair("properties.4736", "Всегда активный"));            
            map_.insert(wstringtranslate_pair("properties.1792", "Единицы изм. min"));
            map_.insert(wstringtranslate_pair("properties.2048", "Единицы изм. max"));
            map_.insert(wstringtranslate_pair("properties.2304", "Единицы изм."));
            map_.insert(wstringtranslate_pair("properties.2560", "Сообщение о включении"));
            map_.insert(wstringtranslate_pair("properties.2816", "Текст сообщения о включении"));
            map_.insert(wstringtranslate_pair("properties.2896", "Сообщение о выключении"));
            map_.insert(wstringtranslate_pair("properties.2976", "Текст сообщения о включении"));
            map_.insert(wstringtranslate_pair("properties.3072", "Тревожное сообщение"));
            map_.insert(wstringtranslate_pair("properties.3073", "Уровень тревожности"));
            map_.insert(wstringtranslate_pair("properties.3328", "Аварийное сообщение"));
            map_.insert(wstringtranslate_pair("properties.3584", "Текст аварийного/тревожного сообщения"));
            map_.insert(wstringtranslate_pair("properties.3840", "Значение тревожности"));
            map_.insert(wstringtranslate_pair("properties.3841", "Значение тревожности"));
            map_.insert(wstringtranslate_pair("properties.4096", "Условие тревожности"));
            map_.insert(wstringtranslate_pair("properties.4097", "Условие тревожности"));
            map_.insert(wstringtranslate_pair("properties.4352", "Архивирование"));
            map_.insert(wstringtranslate_pair("properties.4608", "Мертвая зона архивирования"));
            map_.insert(wstringtranslate_pair("properties.4704", "Уровень доступа"));
            map_.insert(wstringtranslate_pair("properties.4864", "Тип"));
            map_.insert(wstringtranslate_pair("properties.1282", "Статистика"));
            map_.insert(wstringtranslate_pair("properties.609", "Тип источника"));
            map_.insert(wstringtranslate_pair("properties.865", "Адрес"));
            map_.insert(wstringtranslate_pair("properties.1121", "Порт"));
            map_.insert(wstringtranslate_pair("properties.1377", "Номер канала"));
            map_.insert(wstringtranslate_pair("properties.17152", "Имя узла"));
            map_.insert(wstringtranslate_pair("properties.16384", "Имя отчета"));
            map_.insert(wstringtranslate_pair("properties.16400", "Смещение подпериода"));
            map_.insert(wstringtranslate_pair("properties.16416", "Группировка"));
            map_.insert(wstringtranslate_pair("properties.16432", "Ширина столбца"));
            map_.insert(wstringtranslate_pair("properties.16448", "Высота строки"));
            map_.insert(wstringtranslate_pair("properties.16464", "Тип данных"));
            map_.insert(wstringtranslate_pair("properties.16480", "Итог по группировке"));
            map_.insert(wstringtranslate_pair("properties.16496", "Подведение итога"));
            map_.insert(wstringtranslate_pair("properties.16512", "Автопечать"));
            map_.insert(wstringtranslate_pair("properties.16528", "Автозакрытие"));
            map_.insert(wstringtranslate_pair("properties.16640", "Заголовок"));
            map_.insert(wstringtranslate_pair("properties.17424", "Тип итога"));
            map_.insert(wstringtranslate_pair("properties.17440", "Округление"));
            map_.insert(wstringtranslate_pair("properties.17456", "Цвет строки"));
            map_.insert(wstringtranslate_pair("properties.17472", "Цвет текста"));
            map_.insert(wstringtranslate_pair("properties.17488", "Цвет доп."));
            map_.insert(wstringtranslate_pair("properties.17168", "Цвет"));
            map_.insert(wstringtranslate_pair("properties.17184", "Цвет текста"));
            map_.insert(wstringtranslate_pair("properties.17200", "Размер шрифта"));


            map_.insert(wstringtranslate_pair("properties.21008", "Высота графика"));
            map_.insert(wstringtranslate_pair("properties.21024", "Ширина графика"));
            map_.insert(wstringtranslate_pair("properties.21040", "Заполнение"));
            map_.insert(wstringtranslate_pair("properties.21056", "Цвет пера"));
            map_.insert(wstringtranslate_pair("properties.21072", "Цвет заполнения"));


            map_.insert(wstringtranslate_pair("properties.24576", "Провайдер СУБД"));
            map_.insert(wstringtranslate_pair("properties.24592", "Строка подключения"));
            map_.insert(wstringtranslate_pair("properties.24608", "Хост путь"));

            map_.insert(wstringtranslate_pair("clients.ip", "IP"));
            map_.insert(wstringtranslate_pair("clients.host", "Host"));
            map_.insert(wstringtranslate_pair("clients.user", "Пользователь"));
            map_.insert(wstringtranslate_pair("clients.service", "Приложение"));


            map_.insert(wstringtranslate_pair("properties.17408", "Тэг"));
            map_.insert(wstringtranslate_pair("properties.20480", "Имя списка"));
            map_.insert(wstringtranslate_pair("properties.20736", "Имя узла"));
            map_.insert(wstringtranslate_pair("properties.20992", "Тэг"));
            map_.insert(wstringtranslate_pair("properties.21760", "Имя списка"));
            map_.insert(wstringtranslate_pair("AlarmCase.0", ">"));
            map_.insert(wstringtranslate_pair("AlarmCase.1", "<"));
            map_.insert(wstringtranslate_pair("AlarmCase.2", "=="));
            map_.insert(wstringtranslate_pair("AlarmCase.", ""));
            map_.insert(wstringtranslate_pair("AlarmCaseBool.0", "!="));
            map_.insert(wstringtranslate_pair("AlarmCaseBool.1", "!="));
            map_.insert(wstringtranslate_pair("AlarmCaseBool.2", "=="));
            map_.insert(wstringtranslate_pair("AlarmCaseBool.", ""));
            map_.insert(wstringtranslate_pair("AlarmLevel.0", ""));
            map_.insert(wstringtranslate_pair("AlarmLevel.1", "Уведомление"));
            map_.insert(wstringtranslate_pair("AlarmLevel.2", "Тревога"));
            map_.insert(wstringtranslate_pair("AlarmLevel.3", "Авария"));
            map_.insert(wstringtranslate_pair("AlarmLevel.", ""));
            map_.insert(wstringtranslate_pair("TypeTag.0", "Не определен"));
            map_.insert(wstringtranslate_pair("TypeTag.1", "double"));
            map_.insert(wstringtranslate_pair("TypeTag.2", "float"));
            map_.insert(wstringtranslate_pair("TypeTag.3", "num64"));
            map_.insert(wstringtranslate_pair("TypeTag.4", "unum64"));
            map_.insert(wstringtranslate_pair("TypeTag.5", "num32"));
            map_.insert(wstringtranslate_pair("TypeTag.6", "unum32"));
            map_.insert(wstringtranslate_pair("TypeTag.7", "num16"));
            map_.insert(wstringtranslate_pair("TypeTag.8", "unum16"));
            map_.insert(wstringtranslate_pair("TypeTag.9", "num8"));
            map_.insert(wstringtranslate_pair("TypeTag.10", "unum8"));
            map_.insert(wstringtranslate_pair("TypeTag.11", "Дискретный"));
            map_.insert(wstringtranslate_pair("TypeTag.32", "Текст"));
            map_.insert(wstringtranslate_pair("TypeTag.16", "Время"));
            map_.insert(wstringtranslate_pair("TypeTag.17", "Дата"));
            map_.insert(wstringtranslate_pair("TypeTag.259", "Событие(V)"));
            map_.insert(wstringtranslate_pair("TypeTag.128", "Событие"));
            map_.insert(wstringtranslate_pair("TypeTag.258", "Событие(А)"));
            map_.insert(wstringtranslate_pair("TypeTag.65", "Отчетный (год)"));
            map_.insert(wstringtranslate_pair("TypeTag.66", "Отчетный (мин.)"));
            map_.insert(wstringtranslate_pair("TypeTag.67", "Отчетный (час)"));
            map_.insert(wstringtranslate_pair("TypeTag.68", "Отчетный (дек.)"));
            map_.insert(wstringtranslate_pair("TypeTag.69", "Отчетный (сутки)"));
            map_.insert(wstringtranslate_pair("TypeTag.70", "Отчетный (месяц)"));
            map_.insert(wstringtranslate_pair("TypeTag.71", "Отчетный (10 мин.)"));
            map_.insert(wstringtranslate_pair("TypeTag.72", "Отчетный (30 мин.)"));
            map_.insert(wstringtranslate_pair("TypeTag.73", "Отчетный (кварт.)"));
            map_.insert(wstringtranslate_pair("TypeTag.74", "Отчетный (произв.)"));
            map_.insert(wstringtranslate_pair("TypeTag.75", "Отчетный (рез.)"));
            map_.insert(wstringtranslate_pair("TypeTag.", ""));


            map_.insert(wstringtranslate_pair("RWtype.", ""));
            map_.insert(wstringtranslate_pair("RWtype.0", "Полный"));
            map_.insert(wstringtranslate_pair("RWtype.1", "Только чтение"));
            map_.insert(wstringtranslate_pair("RWtype.2", "Только запись"));

            map_.insert(wstringtranslate_pair("RepTagStatisic.0", "Не определено"));
            map_.insert(wstringtranslate_pair("RepTagStatisic.1", "Среднее"));
            map_.insert(wstringtranslate_pair("RepTagStatisic.2", "Интеграл"));
            map_.insert(wstringtranslate_pair("RepTagStatisic.3", "Сумма"));
            map_.insert(wstringtranslate_pair("RepTagStatisic.4", "Min"));
            map_.insert(wstringtranslate_pair("RepTagStatisic.5", "Max"));
            map_.insert(wstringtranslate_pair("RepTagStatisic.6", "Мода"));
            map_.insert(wstringtranslate_pair("RepTagStatisic.0", "Мода"));
            map_.insert(wstringtranslate_pair("TypeGroup.0", "Не определена"));
            map_.insert(wstringtranslate_pair("TypeGroup.", ""));
            map_.insert(wstringtranslate_pair("TypeGroup.4224", "Системная"));
            map_.insert(wstringtranslate_pair("TypeGroup.4225", "Системные переменные"));
            map_.insert(wstringtranslate_pair("TypeGroup.4226", "Вычисляемая"));
            //map_.insert(wstringtranslate_pair("TypeGroup.4227", "Командная"));
            map_.insert(wstringtranslate_pair("TypeGroup.4227", "Отчетная"));
            map_.insert(wstringtranslate_pair("TypeGroup.4228", "Отчетная вычисляемая"));
            map_.insert(wstringtranslate_pair("TypeGroup.8192", "Сетевая"));
            map_.insert(wstringtranslate_pair("TypeGroup.8208", "OPC"));
            map_.insert(wstringtranslate_pair("TypeGroup.8224", "DDE"));
            map_.insert(wstringtranslate_pair("TypeGroup.16416", "MODBUS"));
            map_.insert(wstringtranslate_pair("TypeGroup.16672", "KOYO"));
            map_.insert(wstringtranslate_pair("TypeGroup.16896", "MMS"));
            map_.insert(wstringtranslate_pair("TypeGroup.17152", "IEC60870"));
            map_.insert(wstringtranslate_pair("TypeGroup.16720", "Логика"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.", ""));
            map_.insert(wstringtranslate_pair("RSBoundratetype.110", "110"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.300", "300"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.600", "600"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.1200", "1200"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.2400", "2400"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.4800", "4800"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.9600", "9600"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.14400", "14400"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.19200", "19200"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.38400", "38400"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.56000", "56000"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.57600", "57600"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.115200", "115200"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.128000", "128000"));
            map_.insert(wstringtranslate_pair("RSBoundratetype.256000", "256000"));

            map_.insert(wstringtranslate_pair("KoyoLinkbasetype.", ""));
            map_.insert(wstringtranslate_pair("KoyoLinkbasetype.0", "Hе определен"));
            map_.insert(wstringtranslate_pair("KoyoLinkbasetype.1", "COMPORT"));
            map_.insert(wstringtranslate_pair("KoyoLinkbasetype.2", "TCP"));
            map_.insert(wstringtranslate_pair("KoyoLinkbasetype.3", "UDP"));

            map_.insert(wstringtranslate_pair("KoyoProtocolbasetype.", ""));
            map_.insert(wstringtranslate_pair("KoyoProtocolbasetype.0", "Modbus"));
            map_.insert(wstringtranslate_pair("KoyoProtocolbasetype.1", "DirectNet Hex"));
            map_.insert(wstringtranslate_pair("KoyoProtocolbasetype.2", "DirectNet ASCII"));
            map_.insert(wstringtranslate_pair("KoyoProtocolbasetype.3", "ECOM"));

            map_.insert(wstringtranslate_pair("RSDatabittype.", ""));
            map_.insert(wstringtranslate_pair("RSDatabittype.5", "5"));
            map_.insert(wstringtranslate_pair("RSDatabittype.6", "6"));
            map_.insert(wstringtranslate_pair("RSDatabittype.7", "7"));
            map_.insert(wstringtranslate_pair("RSDatabittype.8", "8"));

            map_.insert(wstringtranslate_pair("RSStopbittype.", ""));
            map_.insert(wstringtranslate_pair("RSStopbittype.0", "1"));
            map_.insert(wstringtranslate_pair("RSStopbittype.1", "1.5"));
            map_.insert(wstringtranslate_pair("RSStopbittype.2", "2"));

            map_.insert(wstringtranslate_pair("RSParitytype.", ""));
            map_.insert(wstringtranslate_pair("RSParitytype.0", "none"));
            map_.insert(wstringtranslate_pair("RSParitytype.1", "odd"));
            map_.insert(wstringtranslate_pair("RSParitytype.2", "even"));
            map_.insert(wstringtranslate_pair("RSParitytype.3", "mark"));
            map_.insert(wstringtranslate_pair("RSParitytype.4", "space"));

            map_.insert(wstringtranslate_pair("Opcvertype.", ""));
            map_.insert(wstringtranslate_pair("Opcvertype.0", "Автоматическое определение"));
            map_.insert(wstringtranslate_pair("Opcvertype.1", "OPCDA 1.0"));
            map_.insert(wstringtranslate_pair("Opcvertype.2", "OPCDA 2.05a"));
            map_.insert(wstringtranslate_pair("Opcvertype.3", "OPCDA 3.0"));

            map_.insert(wstringtranslate_pair("Opccontypetype.", ""));
            map_.insert(wstringtranslate_pair("Opccontypetype.0", "Подписка"));
            map_.insert(wstringtranslate_pair("Opccontypetype.1", "Асинхронно"));
            map_.insert(wstringtranslate_pair("Opccontypetype.2", "Синхронно"));

            map_.insert(wstringtranslate_pair("MBLinkbasetype.", ""));
            map_.insert(wstringtranslate_pair("MBLinkbasetype.0", "не определено"));
            map_.insert(wstringtranslate_pair("MBLinkbasetype.1", "RS232/442/485"));
            map_.insert(wstringtranslate_pair("MBLinkbasetype.2", "TCP"));

            map_.insert(wstringtranslate_pair("LGKProtocolbasetype.", ""));
            map_.insert(wstringtranslate_pair("LGKProtocolbasetype.0", "SPBUS"));
            map_.insert(wstringtranslate_pair("LGKProtocolbasetype.1", "IEK1177"));

            map_.insert(wstringtranslate_pair("MBProtocolbasetype.", ""));
            map_.insert(wstringtranslate_pair("MBProtocolbasetype.0", "RTU"));
            map_.insert(wstringtranslate_pair("MBProtocolbasetype.1", "ASCII"));

            map_.insert(wstringtranslate_pair("LGKLinkbasetype.", ""));
            map_.insert(wstringtranslate_pair("LGKLinkbasetype.0", "не определено"));
            map_.insert(wstringtranslate_pair("LGKLinkbasetype.1", "COMPORT"));

            map_.insert(wstringtranslate_pair("DBProvider.0", "не определено"));
            map_.insert(wstringtranslate_pair("DBProvider.1", "Postgres"));
            map_.insert(wstringtranslate_pair("DBProvider.2", "Oracle"));
            map_.insert(wstringtranslate_pair("DBProvider.3", "MySQL"));
            map_.insert(wstringtranslate_pair("DBProvider.", ""));

            map_.insert(wstringtranslate_pair("GrLocaltype.", ""));
            map_.insert(wstringtranslate_pair("GrLocaltype.0", "По умолчанию"));
            map_.insert(wstringtranslate_pair("GrLocaltype.1", "LOC8"));
            map_.insert(wstringtranslate_pair("GrLocaltype.2", "W16"));
            map_.insert(wstringtranslate_pair("GrLocaltype.3", "W32"));

            map_.insert(wstringtranslate_pair("importform", "Импорт"));
            map_.insert(wstringtranslate_pair("importform.addpreftitle", "Преффикс"));
            map_.insert(wstringtranslate_pair("importform.addpref", "Введите преффикс"));
            map_.insert(wstringtranslate_pair("importform.clear", "Очистить невыделенное"));
            map_.insert(wstringtranslate_pair("importform.rewr", "Перезаписывать существующие"));
            map_.insert(wstringtranslate_pair("importform.pref", "Введение преффикса"));
            map_.insert(wstringtranslate_pair("importform.tag", "  Тэги"));
            map_.insert(wstringtranslate_pair("importform.group", "   Группы"));
            map_.insert(wstringtranslate_pair("importform.agroup", "  Группы алармов"));
            map_.insert(wstringtranslate_pair("importform.user", "  Пользователи"));


            map_.insert(wstringtranslate_pair("filterform", "Фильтрация"));
            map_.insert(wstringtranslate_pair("filterform.title", " Фильтрация по"));
            map_.insert(wstringtranslate_pair("filterform.name", "Имени"));
            map_.insert(wstringtranslate_pair("filterform.comment", "Коментарию"));
            map_.insert(wstringtranslate_pair("filterform.bind", "Привязке"));
            map_.insert(wstringtranslate_pair("filterform.typefilter", "Тип объекта"));
            map_.insert(wstringtranslate_pair("filterform.group", "Группе"));
            map_.insert(wstringtranslate_pair("filterform.itemtype", "Типу"));
            map_.insert(wstringtranslate_pair("filterform.grouptype", "Типу группы"));
            map_.insert(wstringtranslate_pair("filterform.clear", "Очистить"));
            map_.insert(wstringtranslate_pair("filterform.all", "Все"));
            map_.insert(wstringtranslate_pair("addserver", "Соединение"));
            map_.insert(wstringtranslate_pair("addserver.header", "Соединение"));
            map_.insert(wstringtranslate_pair("addserver.host", "Сервер:Порт[:Таймаут=5000]"));
            map_.insert(wstringtranslate_pair("addserver.admin", "Пользователь"));
            map_.insert(wstringtranslate_pair("addserver.pass", "Пароль"));
            map_.insert(wstringtranslate_pair("esdfilter", "Импорт ESD"));
            map_.insert(wstringtranslate_pair("esdfilter.title", "Импорт ESD"));
            map_.insert(wstringtranslate_pair("esdfilter.type", "Тип"));
            map_.insert(wstringtranslate_pair("esdfilter.range", "Диапазон"));
            map_.insert(wstringtranslate_pair("esdfilter.start", "Старт"));
            map_.insert(wstringtranslate_pair("esdfilter.stop", "Стоп"));
            map_.insert(wstringtranslate_pair("mainform", "davinci"));
            map_.insert(wstringtranslate_pair("maintree.unmapprj", "Анмапинг проекта"));
            map_.insert(wstringtranslate_pair("maintree.finder", "Поиск"));
            map_.insert(wstringtranslate_pair("maintree.mapprj", "Мапинг проекта"));
            map_.insert(wstringtranslate_pair("maintree.newprj", "Новый проект"));
            map_.insert(wstringtranslate_pair("maintree.addserver", "Добавить сервер"));
            map_.insert(wstringtranslate_pair("maintree.removeserver", "Удалить сервер"));
            map_.insert(wstringtranslate_pair("maintree.connectserver", "Соединиться"));
            map_.insert(wstringtranslate_pair("maintree.disconnectserver", "Прервать связь"));
            map_.insert(wstringtranslate_pair("maintree.import", "Импорт"));
            map_.insert(wstringtranslate_pair("maintree.export", "Экспорт"));
            map_.insert(wstringtranslate_pair("maintree.additem", "Новый объект"));
            map_.insert(wstringtranslate_pair("maintree.deleteitem", "Удалить"));
            map_.insert(wstringtranslate_pair("maintree.changegroup", "Сменить группу"));
            map_.insert(wstringtranslate_pair("maintree.changeagroup", "Сменить группу тревог"));
            map_.insert(wstringtranslate_pair("maintree.setfitered", "Установить фильтр"));
            map_.insert(wstringtranslate_pair("maintree.resetfitered", "Сбросить фильтр"));
            map_.insert(wstringtranslate_pair("maintree.accessrules", "Правила доступа"));
            map_.insert(wstringtranslate_pair("maintree.clients", "Клиенты"));
            map_.insert(wstringtranslate_pair("maintool.merge", "Закрепить"));
            map_.insert(wstringtranslate_pair("maintree.duplicate", "Клонировать"));
            map_.insert(wstringtranslate_pair("mainwindow.addobject", "Создать"));
            map_.insert(wstringtranslate_pair("mainwindow.namenewobject", "Введите имя нового обьектa"));
            map_.insert(wstringtranslate_pair("mainwindow.namenewobject.group", "Введите имя новой группы"));
            map_.insert(wstringtranslate_pair("mainwindow.namenewobject.agroup", "Введите имя новой группы алармов"));
            map_.insert(wstringtranslate_pair("mainwindow.namenewobject.user", "Введите имя нового пользователя"));
            map_.insert(wstringtranslate_pair("mainwindow.namenewobject.tag", "Введите имя нового тега"));
            map_.insert(wstringtranslate_pair("mainwindow.namenewobject.atag", "Введите имя нового обьектa"));
            map_.insert(wstringtranslate_pair("mainwindow.namenewobject.repheader", "Введите имя новой группы отчетов"));
            map_.insert(wstringtranslate_pair("mainwindow.namenewobject.trendheader", "Введите имя нового узла графиков"));
            map_.insert(wstringtranslate_pair("mainwindow.namenewobject.messheader", "Введите имя нового узла сообщений"));
            map_.insert(wstringtranslate_pair("mainwindow.namenewobject.reparr", "Введите имя нового отчета"));
            map_.insert(wstringtranslate_pair("mainwindow.namenewobject.unit", "Введите имя нового тега отчета"));
            map_.insert(wstringtranslate_pair("mainwindow.namenewobject.trendarr", "Введите имя новой  группы графиков"));
            map_.insert(wstringtranslate_pair("mainwindow.namenewobject.trend", "Введите имя нового тега графика"));


            map_.insert(wstringtranslate_pair("mainwindow.namenewobject.messarr", "Введите имя новой группы сообщений"));
            map_.insert(wstringtranslate_pair("mainwindow.namenewobject.message", "Введите имя новой тега сообщения"));
            map_.insert(wstringtranslate_pair("toolmenue.setviewkindcascade", "Перейти к каскадному виду"));
            map_.insert(wstringtranslate_pair("toolmenue.setviewkindline", "Перейти к древовидному виду"));
            map_.insert(wstringtranslate_pair("toolmenue.clearlog", "Очистить журнал "));
            map_.insert(wstringtranslate_pair("toolmenue.setlogtypeerror", "Включить журнал только ошибок"));
            map_.insert(wstringtranslate_pair("toolmenue.setlogtypeall", "Включить журнал для всех сообщений"));
            map_.insert(wstringtranslate_pair("maintree.servers", "Сервера"));
            map_.insert(wstringtranslate_pair("maintree.local", "Локальный"));
            map_.insert(wstringtranslate_pair("maintree.debug", "Таблицы"));
            map_.insert(wstringtranslate_pair("maintree.maintab", "Теги"));
            map_.insert(wstringtranslate_pair("maintree.groups", "Группы"));
            map_.insert(wstringtranslate_pair("maintree.regapp", "Приложения"));
            map_.insert(wstringtranslate_pair("maintree.command", "Команды"));
            map_.insert(wstringtranslate_pair("maintree.sourse", "Группы"));
            map_.insert(wstringtranslate_pair("maintree.log", "Лог"));
            map_.insert(wstringtranslate_pair("maintree.alarmsourse", "Группа тревог"));
            map_.insert(wstringtranslate_pair("maintree.usersourse", "Пользователи"));
            map_.insert(wstringtranslate_pair("maintree.rulesourse", "Правила доступа"));
            map_.insert(wstringtranslate_pair("maintree.alarm", "Журнал"));
            map_.insert(wstringtranslate_pair("maintree.services", "Службы"));
            map_.insert(wstringtranslate_pair("maintree.activealarm", "Журнал активных тревог"));
            map_.insert(wstringtranslate_pair("metaclient.meta", "Метаданные клиента"));
            map_.insert(wstringtranslate_pair("metaclient.homelist", "Стартовая"));
            map_.insert(wstringtranslate_pair("metaclient.reportlist", "Отчеты"));
            map_.insert(wstringtranslate_pair("metaclient.trendlist", "Тренды"));
            map_.insert(wstringtranslate_pair("metaclient.messagelist", "Сообщения"));
            map_.insert(wstringtranslate_pair("maintable.key", "N"));
            map_.insert(wstringtranslate_pair("maintable.name", "Имя тега"));
            map_.insert(wstringtranslate_pair("maintable.binding", "Привязка"));
            map_.insert(wstringtranslate_pair("maintable.error", "Ошибка"));
            map_.insert(wstringtranslate_pair("maintable.group", "Группа"));
            map_.insert(wstringtranslate_pair("maintable.type", "Тип"));
            map_.insert(wstringtranslate_pair("maintable.val", "Значение"));
            map_.insert(wstringtranslate_pair("maintable.tm", "Время"));
            map_.insert(wstringtranslate_pair("maintable.vl", "Валидность"));
            map_.insert(wstringtranslate_pair("maintable.rc", "Ссылки"));
            map_.insert(wstringtranslate_pair("maintable.comment", "Коментарий"));
            map_.insert(wstringtranslate_pair("maintable.bind", "Привязка"));
            map_.insert(wstringtranslate_pair("maintable.almsg", "Авар. сообщ."));
            map_.insert(wstringtranslate_pair("maintable.onmsg", "Сообщ. вкл."));
            map_.insert(wstringtranslate_pair("maintable.onmsg", "Сообщ. выкл."));
            map_.insert(wstringtranslate_pair("maintable.ue", "Ед изм."));
            map_.insert(wstringtranslate_pair("maintable.logdb", "logdb"));
            map_.insert(wstringtranslate_pair("maintable.mineu", "mineu"));
            map_.insert(wstringtranslate_pair("maintable.maxeu", "maxeu"));
            map_.insert(wstringtranslate_pair("maintable.minraw", "mindev"));
            map_.insert(wstringtranslate_pair("maintable.maxraw", "maxdev"));
            map_.insert(wstringtranslate_pair("maintable.type", "Тип"));
            map_.insert(wstringtranslate_pair("maintable.alcase", "Усл. аларм."));
            map_.insert(wstringtranslate_pair("maintable.alconst", "alconst"));
            map_.insert(wstringtranslate_pair("maintable.logged", "Арх."));
            map_.insert(wstringtranslate_pair("maintable.onmsg", "Сообщ. вкл."));
            map_.insert(wstringtranslate_pair("maintable.offmsg", "Сообщ. выкл."));
            map_.insert(wstringtranslate_pair("maintable.almsg", "Авар. сообщ."));
            map_.insert(wstringtranslate_pair("maintable.alconstmsg", "Трев. сообщ."));
            map_.insert(wstringtranslate_pair("maintable.devdb", "devdb;"));
            map_.insert(wstringtranslate_pair("grouptable.key", "Индекс"));
            map_.insert(wstringtranslate_pair("grouptable.name", "Имя"));
            map_.insert(wstringtranslate_pair("grouptable.appid", "Тип"));
            map_.insert(wstringtranslate_pair("grouptable.сhtype", "тип канала"));
            map_.insert(wstringtranslate_pair("grouptable.сhnum", "номер канала"));
            map_.insert(wstringtranslate_pair("grouptable.valid", "Валидность"));
            map_.insert(wstringtranslate_pair("grouptable.activ", "Активность"));
            map_.insert(wstringtranslate_pair("grouptable.error", "Ошибка"));
            map_.insert(wstringtranslate_pair("logtable.num", "Номер"));
            map_.insert(wstringtranslate_pair("logtable.tm", "Время"));
            map_.insert(wstringtranslate_pair("logtable.msg", "Сообщение"));
            map_.insert(wstringtranslate_pair("logtable.app", "Приложение"));
            map_.insert(wstringtranslate_pair("logtable.lev", "Уровень"));
            map_.insert(wstringtranslate_pair("logtable.app", "Приложение"));
            map_.insert(wstringtranslate_pair("regtable.key", "Ключ"));
            map_.insert(wstringtranslate_pair("regtable.name", "Приложение"));
            map_.insert(wstringtranslate_pair("regtable.evst", "Тип Обсл."));
            map_.insert(wstringtranslate_pair("regtable.msghnd", "Id Очереди"));
            map_.insert(wstringtranslate_pair("commandtable.num", "Номер"));
            map_.insert(wstringtranslate_pair("commandtable.id", "N"));
            map_.insert(wstringtranslate_pair("commandtable.exec", "Тег"));
            map_.insert(wstringtranslate_pair("commandtable.val_bef", "Значение до"));

            map_.insert(wstringtranslate_pair("debuglevproperty.", ""));
            map_.insert(wstringtranslate_pair("debuglevproperty.0", "Минимальный"));
            map_.insert(wstringtranslate_pair("debuglevproperty.1", "Низкий"));
            map_.insert(wstringtranslate_pair("debuglevproperty.2", "Средний"));
            map_.insert(wstringtranslate_pair("debuglevproperty.3", "Высокий"));

            map_.insert(wstringtranslate_pair("application.16", "Администратор"));
            map_.insert(wstringtranslate_pair("application.17", "Сетевой администратор"));
            map_.insert(wstringtranslate_pair("application.4096", "Служба архивирования"));
            map_.insert(wstringtranslate_pair("application.4097", "Системная служба"));
            map_.insert(wstringtranslate_pair("application.8192", "Сетевая служба"));
            map_.insert(wstringtranslate_pair("application.8208", "OPC шлюз"));
            map_.insert(wstringtranslate_pair("application.8224", "DDE шлюз"));
            map_.insert(wstringtranslate_pair("application.16416", "Modbus клиент"));
            map_.insert(wstringtranslate_pair("application.16673", "DirectNet клиент"));
            map_.insert(wstringtranslate_pair("application.16720", "LOGIKA клиент"));
            map_.insert(wstringtranslate_pair("application.10000", "Тест"));

            
            map_.insert(wstringtranslate_pair("alarmtable.num", "Номер"));

            map_.insert(wstringtranslate_pair("alarmtable.num", "Номер"));
            map_.insert(wstringtranslate_pair("alarmtable.tm", "Время"));
            map_.insert(wstringtranslate_pair("alarmtable.id", "Тэг"));
            map_.insert(wstringtranslate_pair("alarmtable.type", "Тип"));
            map_.insert(wstringtranslate_pair("activealarmtable.num", "Номер"));
            map_.insert(wstringtranslate_pair("activealarmtable.tm", "Время"));
            map_.insert(wstringtranslate_pair("activealarmtable.id", "Тэг"));
            map_.insert(wstringtranslate_pair("activealarmtable.kvit", "Квит."));
            map_.insert(wstringtranslate_pair("activealarmtable.off", "Выкл."));
            
            map_.insert(wstringtranslate_pair("accessrule.filter", "IP фильтр"));
            map_.insert(wstringtranslate_pair("accessrule.name", "Имя правила"));            
            map_.insert(wstringtranslate_pair("accessrule.user", "Пользователь")); 
            map_.insert(wstringtranslate_pair("accessrule.host", "Хост"));            
            map_.insert(wstringtranslate_pair("accessrule.rule", "Правило"));             
            map_.insert(wstringtranslate_pair("accessrule.role", "Роль"));
            map_.insert(wstringtranslate_pair("accessrule.accesslev", "Уровень доступа"));
            
            map_.insert(wstringtranslate_pair("usertable.name", "Имя"));
            map_.insert(wstringtranslate_pair("usertable.password", "Пароль"));
            map_.insert(wstringtranslate_pair("usertable.level", "Уровень"));
            map_.insert(wstringtranslate_pair("usertable.filter", "IP фильтр"));
            map_.insert(wstringtranslate_pair("usertable.role", "Роль"));            
            
            
            map_.insert(wstringtranslate_pair("agrouptable.name", "Имя"));
            map_.insert(wstringtranslate_pair("valchtable.key", "Ключ"));
            map_.insert(wstringtranslate_pair("valchtable.name", "Черти че"));
            map_.insert(wstringtranslate_pair("valchtable.val", "Значение"));
            map_.insert(wstringtranslate_pair("commandtable.key", "Ключ"));
            map_.insert(wstringtranslate_pair("commandtable.name", "Имя"));
            map_.insert(wstringtranslate_pair("commandtable.val", "Значение"));
            map_.insert(wstringtranslate_pair("commandtable.preval", "Предзначение"));
            map_.insert(wstringtranslate_pair("error.274", "Ошибка дублировния имени"));
            map_.insert(wstringtranslate_pair("error.275", "Задаваемое имя некорректно"));
            map_.insert(wstringtranslate_pair("error.277", "Родительский объект не существует"));
            map_.insert(wstringtranslate_pair("error.278", "Объект непуст и не может быть удален"));
            map_.insert(wstringtranslate_pair("error.279", "Объект с таким типом уже существует"));
            map_.insert(wstringtranslate_pair("error.280", "Соединение с источником данных утрачено"));
            map_.insert(wstringtranslate_pair("error.281", "Не удалось связаться с удаленной базой"));
            map_.insert(wstringtranslate_pair("error.1064", "Ошибка разбора ответа с источника"));
            map_.insert(wstringtranslate_pair("trasaction.1019", "Изменение свойств прошло успешно."));
            map_.insert(wstringtranslate_pair("trasaction.1039", "Добавление было успешным."));
            map_.insert(wstringtranslate_pair("trasaction.1040", "Удаление было успешным."));
            map_.insert(wstringtranslate_pair("trasaction.1041", "Изменение группы тега было успешным."));
            map_.insert(wstringtranslate_pair("trasaction.1048", "Изменение алармовой группы тега было успешным.Увеличить "));
            map_.insert(wstringtranslate_pair("viewtable.inccnt", "Увеличить общее количество ссылок"));
            map_.insert(wstringtranslate_pair("viewtable.deccnt", "Уменьшить общее количество ссылок"));
            map_.insert(wstringtranslate_pair("viewtable.allvalid", "Сделать все валидным"));
            map_.insert(wstringtranslate_pair("viewtable.allinvalid", "Сбросить всю валидность"));
            map_.insert(wstringtranslate_pair("viewtable.kvit", "Квитирование"));
            map_.insert(wstringtranslate_pair("viewtable.group_kvit", "Квитирование группы"));
            map_.insert(wstringtranslate_pair("viewtable.agroup_kvit", "Квитирование алармовой группы"));
            map_.insert(wstringtranslate_pair("setvalue.header", "Установка тега"));
            map_.insert(wstringtranslate_pair("setvalue.setvalue", "Устанока значения"));
            map_.insert(wstringtranslate_pair("setvalue.setcommand", "Команда"));
            map_.insert(wstringtranslate_pair("setvalue.inccnt", "Увеличить кол-во ссылок"));
            map_.insert(wstringtranslate_pair("setvalue.deccnt", "Уменьшить кол-во ссылок"));
            map_.insert(wstringtranslate_pair("setvalue.valid", "Сделать валидным"));
            map_.insert(wstringtranslate_pair("setvalue.invalid", "Сбросить валидность"));
            map_.insert(wstringtranslate_pair("error.518", "Ошибка авторизации"));
            map_.insert(wstringtranslate_pair("error.519", "Не удалось связаться с базой"));
            map_.insert(wstringtranslate_pair("error.512", "Тег не найден"));
            map_.insert(wstringtranslate_pair("error.513", "Ошибка разбора выражения "));
            map_.insert(wstringtranslate_pair("error.514", "Ошибка операции выражения"));
            map_.insert(wstringtranslate_pair("error.519", "Не удалось связаться с базой"));
            map_.insert(wstringtranslate_pair("error.520", "Тип не поддерживается сервисом"));
            map_.insert(wstringtranslate_pair("error.521", "Ошибка привязки"));
            map_.insert(wstringtranslate_pair("error.525", "Невозможно свести тип к требуемому"));
			map_.insert(wstringtranslate_pair("error.1060", "Cвязь установлена, но протокол не инициализирован"));
			map_.insert(wstringtranslate_pair("error.1060", "Тип канала не поддерживается серером или пуст"));
			map_.insert(wstringtranslate_pair("error.1062", "Нет соединения с устройством"));
            map_.insert(wstringtranslate_pair("error.3", "Не удалось связаться с базой в каталоге:"));
            map_.insert(wstringtranslate_pair("trasaction.1006", "Содинение с базой"));
            map_.insert(wstringtranslate_pair("trasaction.1017", "Запрос к базе    "));
            map_.insert(wstringtranslate_pair("maintree.startservice", "Запустить сервис"));
            map_.insert(wstringtranslate_pair("maintree.stopservice", "Остановить сервис"));
            map_.insert(wstringtranslate_pair("Sevicestarttype.0", "Не определен"));
            map_.insert(wstringtranslate_pair("Sevicestarttype.1", "Выключена"));
            map_.insert(wstringtranslate_pair("Sevicestarttype.2", "Вручную"));
            map_.insert(wstringtranslate_pair("Sevicestarttype.3", "Автоматически"));
            map_.insert(wstringtranslate_pair("Sevicestarttype.4", "Системно"));
            map_.insert(wstringtranslate_pair("Sevicestarttype.5", "Низкоуровнево"));
            map_.insert(wstringtranslate_pair("Sevicestarttype.", ""));
//#endif
        }}}
